eureka:
  client:
    enabled: true
    register-with-eureka: 'true'
    fetch-registry: 'true'
    service-url:
      defaultZone:
  instance:
    prefer-ip-address: 'true'

spring:
  application:
    name: notification-service